# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-28 16:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MainGallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='Başlık')),
                ('content', models.TextField(verbose_name='İçerik Bilgisi')),
                ('image', models.ImageField(upload_to='', verbose_name='Galerinin Ana Resmi')),
                ('link', models.URLField(verbose_name='Link')),
            ],
        ),
    ]
