# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-27 16:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SliderImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='')),
                ('title', models.CharField(max_length=250)),
                ('link1', models.CharField(max_length=250)),
                ('link1_title', models.CharField(max_length=25)),
                ('link2', models.CharField(max_length=250)),
                ('link2_title', models.CharField(max_length=25)),
            ],
        ),
    ]
